spring:
  application:
    name: UserCrudApp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres_db}
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    default-schema: user_crud
    liquibase-schema: user_crud_migrations

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${spring.liquibase.default-schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
  file:
    name: user_crud.log
    path: /logs/product-service/

server:
  port: 8080
app:
  image:
    bucket: C:\Users\79213\IdeaProjects\temp\UserCrudTask\images